### ISSUE TITLE
Cannot link or deploy project

### ISSUE THREAD

**Issue by danngossinga** [nuxt-hub/cli#29]
Hi,

Since today i cannot link or deploy via nuxthub cli. I have try to deploy on a fresh project but I always get an error. Also, the cli require authentication every time i try to deploy even when already done few seconds ago.
<img width="903" alt="Capture d’écran, le 2024-09-21 à 20 38 30" src="https://github.com/user-attachments/assets/c67234bf-3b88-4181-b627-347cb9aabe18">

**Comment by atinux** [comment]
Could you try the [v0.6.2](https://github.com/nuxt-hub/cli/releases/tag/0.6.2) with:

```bash
DEBUG=1 nuxthub deploy
```

**Comment by atinux** [comment]
It is now fixed in `v0.6.3`, sorry about this, it was related to an upgrade of `ofetch`
