### ISSUE TITLE
`nuxthub deploy --dotenv` ignored

### ISSUE THREAD

**Issue by angelorc** [nuxt-hub/cli#30]
## Description

The `nuxthub deploy` command includes the `--dotenv` flag, but this flag is ignored during the `linkedProject` phase. Upon inspecting the code at [this line](https://github.com/nuxt-hub/cli/blob/main/src/commands/deploy.mjs#L52) and the `fetchProject()` function at [this line](https://github.com/nuxt-hub/cli/blob/main/src/utils/data.mjs#L179), it is evident that the `--dotenv` flag is not taken into account. Instead, the `fetchProject` function utilizes `process.env`.

Currently, the `--dotenv` flag is only considered during the build phase.

This logic becomes cumbersome when managing three different environments:

- Local
- Preview
- Production

Ideally, each command should consider the `--dotenv` flag to facilitate smoother environment management.

## Steps to Reproduce

1. Use the `nuxthub deploy` command with the `--dotenv` flag.
2. Observe that the environment variables specified in the dotenv file are not applied during the `linkedProject` phase. `No project is linked with the NUXT_HUB_PROJECT_KEY environment variable.`

## Expected Behavior

The `--dotenv` flag should be considered during all phases of the `nuxthub deploy` command, including the `linkedProject` phase.

## Actual Behavior

The `--dotenv` flag is ignored during the `linkedProject` phase, and only considered during the build phase.

**Comment by bytecod3r** [comment]
it seems this is not working yet, providing --dotenv envfile does not populate the env variables within the dashboard https://admin.hub.nuxt.com/[user_id]/settings/environment and subsequently no env variables were pushed into Cloudflare.

**Comment by atinux** [comment]
Oh my bad @bytecod3r, I thought this was only for the build phase.

But would you overwrite the env variables if already defined on Cloudflare? What about secrets defined there too?
