### ISSUE TITLE
`nuxthub preview` doesn't apply migrations

### ISSUE THREAD

**Issue by ipanamski** [nuxt-hub/cli#36]
Running `nuxthub preview` was not applying my migrations locally from `server/database/migrations`.
I had to manually copy `server/database` to the `dist` folder.
Then I ran `npx wrangler --config dist/wrangler.toml d1 migrations apply default` and they got successfully applied.

Module versions:
```
"nuxt": "^3.14.1592"
"@nuxthub/core": "^0.7.37"
"nuxthub": "^0.7.3"
"wrangler": "^3.89.0"
```

**Comment by atinux** [comment]
The migrations are since NuxtHub 0.8: https://hub.nuxt.com/changelog/database-migrations
