### ISSUE TITLE
`nuxthub init` fails on win32 arm64 LE

### ISSUE THREAD

**Issue by BastianBrouwers** [nuxt-hub/cli#39]
# `nuxthub init` fails on win32 arm64 LE

Im not sure if there is a way around this or if we have to wait for an update on `workerd` to support arm64.

```
C:\develop\private\test\nuxthub-app\node_modules\.pnpm\workerd@1.20241022.0\node_mod…  
│     throw new Error(`Unsupported platform: ${platformKey}`);
│           ^
│ Error: Unsupported platform: win32 arm64 LE
│     at pkgAndSubpathForCurrentPlatform (C:\develop\private\test\nuxthub-app\node_mod…  
│     at checkAndPreparePackage (C:\develop\private\test\nuxthub-app\node_modules\.pnp…  
│     at Object.<anonymous> (C:\develop\private\test\nuxthub-app\node_modules\.pnpm\wo…  
│     at Module._compile (node:internal/modules/cjs/loader:1469:14)
│     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
│     at Module.load (node:internal/modules/cjs/loader:1288:32)
│     at Module._load (node:internal/modules/cjs/loader:1104:12)
│     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:1…  
│     at node:internal/main/run_main_module:28:49
│ Node.js v20.18.1
└─ Failed in 144ms at C:\develop\private\test\nuxthub-app\node_modules\.pnpm\workerd@1.20241022.0\node_modules\workerd
node_modules/.pnpm/esbuild@0.17.19/node_modules/esbuild: Running postinstall script...   
node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild: Running postinstall script...    
node_modules/.pnpm/esbuild@0.24.0/node_modules/esbuild: Running postinstall script...    
 ELIFECYCLE  Command failed with exit code 1.
```

## My Setup:
Microsoft Windows 11 Home
Version 10.0.26100 Build 26100
ARM64-based PC
System-SKU Surface_Laptop_7th_Edition_2037

**Comment by RihanArfan** [comment]
Unfortunately workerd doesn't support arm64 on Windows yet. [https://github.com/cloudflare/workerd/issues/2735](https://github.com/cloudflare/workerd/issues/2735)

Cloudflare do publish a [Linux ARM build of workerd](https://github.com/cloudflare/workerd/tree/main/npm/workerd-linux-arm64). Does running within WSL work?

**Comment by BastianBrouwers** [comment]
> Unfortunately workerd doesn't support arm64 on Windows yet. [cloudflare/workerd#2735](https://github.com/cloudflare/workerd/issues/2735)
> 
> Cloudflare do publish a [Linux ARM build of workerd](https://github.com/cloudflare/workerd/tree/main/npm/workerd-linux-arm64). Does running within WSL work?

Thank you for your response!
Im not too experienced with WSL and its setup. I would have to give this a try.

**Comment by BastianBrouwers** [comment]
Good news: WSL did seem to work: `wsl -d ubuntu` -> `nuxthub init`:

![image](https://github.com/user-attachments/assets/f72ade27-66b3-4851-abfe-e2c1f403d38e)

![image](https://github.com/user-attachments/assets/d3e49d81-c71b-4fad-8254-9f3f4ca1941f)
